### ISSUE TITLE
[Epic] WatchTower run with ZERO errors

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/watch-tower#2]
WatchTower has many errors that are thrown to our alert/log system.

These errors are most of the time false positives of cases we want to handle better. 

# Handle special cases
This epic will point to some initiatives that would handle these cases.

- [x] Handle Specific TWAP logic: 
   - [x] Handle Specific smart order validations (prep for TWAP handling): https://github.com/cowprotocol/composable-cow/pull/56
   - [x] So TWAP orders that will never be created are not re-checked in each block
        - [x] Order is Expired (we don't need to keep checking, this order will never be created)
   - [x] Reduce the checking frequency for TWAP
       - [x]  Non need to check on every block, we know the start time for each chunk
- [x] #6
- [x] Handle Conditional Order cancellations (or missing `auth`): https://github.com/cowprotocol/composable-cow/pull/52 
- [x] Do not delete orders that fails for UNKNOWN reason (so its re-attempted later): https://github.com/cowprotocol/composable-cow/pull/46
- [x] Handle `DuplicatedOrder` on the Orderbook API: It should not be an errors, since it just mean that someone else already published it https://github.com/cowprotocol/composable-cow/pull/40 

# Improve Logging / Monitoring
Also, as part of this effort on improving logging end monitoring:
- [x] Allow to debug locally with Production State: https://github.com/cowprotocol/composable-cow/pull/54
- [x] Create a DEV environment to be able to re-iterate the watch-tower: https://github.com/cowprotocol/composable-cow/pull/45 
- [x] Add sentry, to overcome shortcomings of Tenderly logs and improve our observability/debug experience: https://github.com/cowprotocol/composable-cow/pull/43 
- [x] Allow to re-process old blocks, to re-create a failure indexing an order locally https://github.com/cowprotocol/composable-cow/pull/41 
- [x] Do not fail in intermediate errors processing events, but fail if there was at least one error so Tenderly can show the FAILED STATUS: https://github.com/cowprotocol/composable-cow/pull/36  
- [x] Handle errors writing in Tenderly Storage: https://github.com/cowprotocol/composable-cow/pull/53 

# Other MISC
- [x] Add CLA: see https://github.com/cowprotocol/cla

**Comment by mfw78** [comment]
I've removed merkle support from this list as it's being tracked by the epic https://github.com/cowprotocol/pm/issues/9
